stages:
  - build
  - release

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build_job:
  stage: build
  image: gradle:7.3-jdk17-alpine
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  script: gradle -Pversion=$CI_COMMIT_TAG build
  artifacts:
    paths:
      - build/libs
  cache:
    key: "$CI_COMMIT_TAG"
    policy: push
    paths:
      - build
      - .gradle

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  needs:
    - job: build_job
      artifacts: true
  script:
    - echo "running release_job"
  release:                               # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
    assets:
      links:
      - name: 'Mod Download'
        url: 'https://gitlab.jagenka.de/jagenka/deathgames-server-mod/-/jobs/$CI_JOB_ID/artifacts/file/build/libs/deathgames-server-mod-$CI_COMMIT_TAG.jar'
