stages:
  - build
  - release

build_job:
  stage: build
  image: alpine
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  script: ./gradlew build
  artifacts:
    paths:
      - build/libs

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build_job
      artifacts: true
  script:
    - echo "running release_job"
  release:                               # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
    assets:
      links:
      - name: 'mod'
        url: 'https://gitlab.jagenka.de/jagenka/deathgames-server-mod/-/jobs/${GE_JOB_ID}/artifacts/file/build/libs/'
